export const categories = [
  { id: 'cat-electronics', label: 'Electronics', icon: '📱' },
  { id: 'cat-fashion', label: 'Fashion', icon: '👕' },
  { id: 'cat-home', label: 'Home', icon: '🏠', muted: true },
  { id: 'cat-books', label: 'Books', icon: '📚' },
  { id: 'cat-sports', label: 'Sports', icon: '⚽' },
  { id: 'cat-gaming', label: 'Gaming', icon: '🎮' },
];

export const deals = [
  {
    id: 'p-smartphone',
    title: 'Smartphone XZ Pro',
    badge: '24% OFF',
    rating: '4.5',
    ratingCount: '2.3k',
    priceCurrent: '₹18,999',
    priceMrp: '₹24,999',
    offText: '24% off',
    wide: false,
    icon: '',
  },
  {
    id: 'p-laptop',
    title: 'Laptop Ultra Slim',
    badge: '27% OFF',
    rating: '4.3',
    ratingCount: '1.8k',
    priceCurrent: '₹45,999',
    priceMrp: '₹62,999',
    offText: '27% off',
    wide: false,
    icon: '',
  },
  {
    id: 'p-watch',
    title: 'Smart Watch Pro',
    badge: '42% OFF',
    rating: '4.6',
    ratingCount: '3.2k',
    priceCurrent: '₹3,499',
    priceMrp: '₹5,999',
    offText: '42% off',
    wide: true,
    icon: '⌚',
  },
  {
    id: 'p-earbuds',
    title: 'Wireless Earbuds',
    badge: '43% OFF',
    rating: '4.4',
    ratingCount: '5.1k',
    priceCurrent: '₹1,999',
    priceMrp: '₹3,499',
    offText: '43% off',
    wide: true,
    icon: '🎧',
  },
];

export const recommended = [
  {
    id: 'r-shirt',
    title: 'Cotton T-Shirt',
    badge: '50% OFF',
    rating: '4.2',
    ratingCount: '892',
    priceCurrent: '₹499',
    priceMrp: '₹999',
    offText: '50% off',
    icon: '👕',
  },
  {
    id: 'r-shoes',
    title: 'Running Shoes',
    badge: '50% OFF',
    rating: '4.5',
    ratingCount: '1.5k',
    priceCurrent: '₹2,499',
    priceMrp: '₹4,999',
    offText: '50% off',
    icon: '👟',
  },
  {
    id: 'r-camera',
    title: 'Digital Camera HD',
    badge: '28% OFF',
    rating: '4.7',
    ratingCount: '672',
    priceCurrent: '₹28,999',
    priceMrp: '₹39,999',
    offText: '28% off',
    icon: '📷',
  },
  {
    id: 'r-backpack',
    title: 'Travel Backpack',
    badge: '48% OFF',
    rating: '4.3',
    ratingCount: '1.1k',
    priceCurrent: '₹1,299',
    priceMrp: '₹2,499',
    offText: '48% off',
    icon: '🎒',
  },
];
